# Generated by Django 2.1.1 on 2019-11-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
    ]
