# Generated by Django 2.1.1 on 2019-11-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbooks', '0003_auto_20191109_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(help_text='13 글자로 이루어진 <a href="https://www.isbn-international.org/content/what-isbn">ISBN 넘버를 입력하시오!</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbooks.Author')),
                ('genre', models.ManyToManyField(help_text='장르를 선택하시오!', to='openbooks.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbooks.Language')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='한 권의 책에게만 부여되는 고유한 ID입니다', primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='간단한 책 설명 부탁드립니다!', max_length=1000)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('rent_availability', models.BooleanField()),
                ('donate_availability', models.BooleanField()),
                ('reserved', models.DateTimeField(auto_now=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbooks.Book')),
            ],
            options={
                'ordering': ['-due'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bookinstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbooks.BookInstance')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_person', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
